" ALFABETO GRIEGO

iab gA          Α
iab gB          Β
iab gG          Γ
iab gD          Δ
iab gE          Ε
iab gZ          Ζ
iab gH          Η
iab gTH         Θ
iab gI          Ι
iab gK          Κ
iab gL          Λ
iab gM          Μ
iab gN          Ν
iab gX          Ξ
iab gO          Ο
iab gP          Π
iab gR          Ρ
iab gS          Σ
iab gT          Τ
iab gU          Υ
iab gF          Φ
iab gC          Χ
iab gPS         Ψ
iab gW          Ω

iab Alpha       Α
iab Beta        Β
iab Gamma       Γ
iab Delta       Δ
iab Epsilon     Ε
iab Zeta        Ζ
iab Eta         Η
iab Theta       Θ
iab Iota        Ι
iab Kappa       Κ
iab Lambda      Λ
iab Mu          Μ
iab Nu          Ν
iab Xi          Ξ
iab Omicron     Ο
iab Pi          Π
iab Rho         Ρ
iab Sigma       Σ
iab Tau         Τ
iab Upsilon     Υ
iab Phi         Φ
iab Chi         Χ
iab Psi         Ψ
iab Omega       Ω


iab ga     α
iab gb     β
iab gg     γ
iab gd     δ
iab ge     ε
iab gz     ζ
iab gh     η
iab gth    θ
iab gi     ι
iab gk     κ
iab gl     λ
iab gm     μ
iab gn     ν
iab gx     ξ
iab go     ο
iab gp     π
iab gr     ρ
iab gs     σ
iab gt     τ
iab gu     υ
iab gf     φ
iab gc     χ
iab gps    ψ
iab gw     ω

iab alpha       α
iab beta        β
iab gamma       γ
iab delta       δ
iab epsilon     ε
iab zeta        ζ
iab eta         η
iab theta       θ
iab iota        ι
iab kappa       κ
iab lambda      λ
iab mu          μ
iab nu          ν
iab xi          ξ
iab omicron     ο
iab pi          π
iab rho         ρ
iab sigma       σ
iab tau         τ
iab upsilon     υ
iab phi         φ
iab chi         χ
iab psi         ψ
iab omega       ω

" NEGRITAS

iab ba          𝗮
iab bb          𝗯
iab bc          𝗰
iab bd          𝗱
iab be          𝗲
iab bf          𝗳
iab bg          𝗴
iab bh          𝗵
iab bi          𝗶
iab bj          𝗷
iab bk          𝗸
iab bl          𝗹
iab bm          𝗺
iab bn          𝗻
iab bo          𝗼
iab bp          𝗽
iab bq          𝗾
iab br          𝗿
iab bs          𝘀
iab bt          𝘁
iab bu          𝘂
iab bv          𝘃
iab bw          𝘄
iab bx          𝘅
iab by          𝘆
iab bz          𝘇

iab bA          𝗔
iab bB          𝗕
iab bC          𝗖
iab bD          𝗗
iab bE          𝗘
iab bF          𝗙
iab bG          𝗚
iab bH          𝗛
iab bI          𝗜
iab bJ          𝗝
iab bK          𝗞
iab bL          𝗟
iab bM          𝗠
iab bN          𝗡
iab bO          𝗢
iab bP          𝗣
iab bQ          𝗤
iab bR          𝗥
iab bS          𝗦
iab bT          𝗧
iab bU          𝗨
iab bV          𝗩
iab bW          𝗪
iab bX          𝗫
iab bY          𝗬
iab bZ          𝗭
iab b0          𝟬

" SIBOLOS RANDOM

iab star        ★
iab bbox        ■
iab sbox        ▫
iab sbbox       ▪
iab square      □
iab bsquare     ■
iab ssquare     ▫
iab sbsquare    ▪
iab diamond     ◇
iab bdiamond    ◆
iab lozenge     ◊
iab circ        ○
iab circle      ○
iab bcircle     ●
iab dcircle     ◌
iab triangle    △
iab btriangle   ▲

iab sun         ☼
iab rightmoon   ☽
iab leftmoon    ☾
iab female      ♀
iab male        ♂

" BASICO

iab add         +
iab plus        +
iab min         -
iab pm          ±
iab mp          ∓
iab sum         ∑
iab prod        ∏
iab coprod      ∐
iab =~          ≃
iab approx      ≈
iab ~~          ≈
iab neq         ≠
iab !=          ≠
iab /=          ≠
iab equiv       ≡
iab eq          =
iab leq         ≤
iab <=          ≤
iab geq         ≥
iab >=          ≥
iab qed         ∎
iab ast         ∗
iab times       ×
iab XX          ×
iab div         ÷
iab comp        ∘
iab dot         ·
iab cdot        ·
iab rt          √
iab rt3         ∛
iab rt4         ∜
iab inf         ∞
iab oo          ∞
iab propto      ∝
iab pitchfork   ⋔
iab lceil       ⌈
iab rceil       ⌉
iab lfloor      ⌊
iab rfloor      ⌋
iab langle      ⟨
iab rangle      ⟩
iab llens       ⦇
iab rlens       ⦈
" iab [[          ⟦
" iab ]]          ⟧

" LOGICA

iab AA          ∀
iab EE          ∃
iab forall      ∀
iab exists      ∃
iab nexists     ∄
iab land        ∧
iab and         ∧
iab lor         ∨
iab or          ∨
iab lnot        ¬
iab not         ¬
iab neg         ¬
iab top         ⊤
iab bot         ⊥
iab multimap    ⊸
iab multimapinv ⟜
iab invmultimap ⟜
iab parr        ⅋
iab invamp      ⅋
iab therefore   ∴
iab because     ∵

" CONJUNTOS

iab in          ∈
iab notin       ∉

iab inters      ∩
iab cap         ∩
iab nn          ∩
iab union       ∪
iab cup         ∪
iab uu          ∪
iab subset      ⊂
iab supset      ⊃
iab nsubset     ⊄
iab nsupset     ⊅
iab subseteq    ⊆
iab supseteq    ⊇
iab nsubseteq   ⊈
iab nsupseteq   ⊉
iab sqsubset    ⊏
iab sqsupset    ⊐
iab sqsubseteq  ⊑
iab sqsupseteq  ⊒
iab sqcap       ⊓
iab sqcup       ⊔

iab empty       ∅
iab NN          ℕ
iab ZZ          ℤ
iab QQ          ℚ
iab RR          ℝ
iab CC          ℂ
iab PP          ℙ
iab BB          𝔹
iab HH          ℍ
iab NN          ℕ
iab ZZ          ℤ
iab QQ          ℚ
iab RR          ℝ
iab CC          ℂ
iab PP          ℙ
iab BB          𝔹
iab HH          ℍ

" CALCULO

iab nabla       ∇
iab grad        ∇
iab partial     𝜕
iab part        𝜕
iab int         ∫
iab iint        ∬
iab iiint       ∭
iab oint        ∮
iab oiint       ∯
iab oiiint      ∰
iab dev         d/d
iab devp        𝜕/𝜕

" TENSORES

iab oplus       ⊕
iab ominus      ⊖
iab otimes      ⊗
iab oslash      ⊘
iab odot        ⊙
iab ocirc       ⊚
iab oast        ⊛
iab oequal      ⊜
iab o+          ⊕
iab o-          ⊖
iab ox          ⊗
iab o/          ⊘
iab o.          ⊙
iab o*          ⊛
iab o=          ⊜

" PUNTOS

iab ldots       …
iab ...          …
iab cdots       ⋯
iab vdots       ⋮
iab iddots      ⋰
iab ddots       ⋱

" FLECHAS

iab mapsto       ↦
iab inject       ↪
iab to           →
iab ->           →
iab <-           ←
iab -v           ↓
iab -^           ↑
iab <->          ↔
iab ^-v          ↕
iab =>           ⇒
iab =<           ⇐
iab =v           ⇓
iab =^           ⇑
iab <=>          ⇔
iab iff          ⇔
iab ^=v          ⇕

" FRACCIONES

iab f14          ¼
iab f12          ½
iab f34          ¾
iab f13          ⅓
iab f23          ⅔
iab f15          ⅕
iab f25          ⅖
iab f35          ⅗
iab f45          ⅘
iab f16          ⅙
iab f56          ⅚
iab f18          ⅛
iab f38          ⅜
iab f58          ⅝
iab f78          ⅞

" SUBINDICES Y SUPERINDICES

iab _a          ₐ
iab _e          ₑ
iab _h          ₕ
iab _i          ᵢ
iab _j          ⱼ
iab _k          ₖ
iab _l          ₗ
iab _m          ₘ
iab _n          ₙ
iab _o          ₒ
iab _p          ₚ
iab _r          ᵣ
iab _s          ₛ
iab _t          ₜ
iab _u          ᵤ
iab _v          ᵥ
iab _x          ₓ

iab _0          ₀
iab _1          ₁
iab _2          ₂
iab _3          ₃
iab _4          ₄
iab _5          ₅
iab _6          ₆
iab _7          ₇
iab _8          ₈
iab _9          ₉
iab _+           ₊
iab _-           ₋
iab _=           ₌
iab _(           ₍
iab _)           ₎

iab ^a           ᵃ
iab ^b           ᵇ
iab ^c           ᶜ
iab ^d           ᵈ
iab ^e           ᵉ
iab ^f           ᶠ
iab ^g           ᵍ
iab ^h           ʰ
iab ^i           ⁱ
iab ^j           ʲ
iab ^k           ᵏ
iab ^l           ˡ
iab ^m           ᵐ
iab ^n           ⁿ
iab ^o           ᵒ
iab ^p           ᵖ
iab ^r           ʳ
iab ^s           ˢ
iab ^t           ᵗ
iab ^u           ᵘ
iab ^v           ᵛ
iab ^w           ʷ
iab ^x           ˣ
iab ^y           ʸ
iab ^z           ᶻ

iab ^A           ᴬ
iab ^B           ᴮ
iab ^D           ᴰ
iab ^E           ᴱ
iab ^G           ᴳ
iab ^H           ᴴ
iab ^I           ᴵ
iab ^J           ᴶ
iab ^K           ᴷ
iab ^L           ᴸ
iab ^M           ᴹ
iab ^N           ᴺ
iab ^O           ᴼ
iab ^P           ᴾ
iab ^R           ᴿ
iab ^T           ᵀ
iab ^U           ᵁ
iab ^V           ⱽ
iab ^W           ᵂ
iab ^0           ⁰
iab ^1           ¹
iab ^2           ²
iab ^3           ³
iab ^4           ⁴
iab ^5           ⁵
iab ^6           ⁶
iab ^7           ⁷
iab ^8           ⁸
iab ^9           ⁹
iab ^+           ⁺
iab ^-           ⁻
iab ^=           ⁼
iab ^(           ⁽
iab ^)           ⁾
iab inv         ⁻¹
